export const UI_STRINGS = {
  APP_TITLE: "KaosGdd",
  TASKS: "Tasks",
  REMINDERS: "Reminders",
  TASK_DETAIL: "Task Detail",
  REMINDER_DETAIL: "Reminder Detail",
  TASK_LIST: "Task list",
  NO_TASKS: "No tasks yet.",
  ADD_TASK: "Add task",
  ADD_REMINDER: "Reminder",
  ADD: "Add",
  ADDING: "Adding...",
  SAVE: "Save",
  SAVING: "Saving...",
  DONE: "Done",
  UNDO: "Undo",
  BACK_TO_TASKS: "< Back to Task",
  BACK_TO_TASKS_LIST: "< Back to Tasks List",
  BACK_TO_REMINDERS_LIST: "< Back to Reminders List",
  TASK_NOT_FOUND: "Task not found.",
  REMINDER_NOT_FOUND: "Reminder not found.",
  BACKEND_UNREACHABLE: "backend unreachable",
  REMINDER_LIST: "Reminders",
  REMINDER_SHORT: "r",
  NO_REMINDERS: "No reminders.",
  ACK: "Ack",
  SNOOZE_10M: "Snooze 10m",
  CANCEL: "Cancel",
  ACTIVE: "active",
  DONE_STATE: "done",
  DUE: "d",
  MEMO: "Memo",
  CREATED: "created",
  UPDATED: "updated",
  STATE: "state",
  REMIND_AT: "remind_at",
  RAW_EDIT: "Raw Edit",
  TITLE: "title",
  EDIT_TASK: "Edit",
  MORE: "More",
  ID: "item ID",
  COPY_ID: "Copy ID",
  COPIED: "Copied",
};