export const UI_STRINGS = {
  APP_TITLE: "KaosGdd",
  APP_TITLE_WEB: "KaosGdd Web",
  APP_DESCRIPTION: "Tailscale-only web UI for KaosGdd",
  APP_HEADER_SUBTITLE: "Order for Chaotic-Minded Gdd",
  HOME_SUBTITLE: "Tailscale-only internal web app",
  HOME: "Home",
  SYSTEM: "System",
  BACKEND: "Backend",
  APP: "App",
  STATUS_OK: "OK",
  STATUS_DOWN: "DOWN",
  TASKS_LIVE: "Tasks Live",
  EVENT_NOT_FOUND: "Event not found.",
  FILE_NOT_FOUND: "File not found.",
  NOTE_NOT_FOUND: "Note not found.",
  TITLE_REQUIRED_UI: "Title is required.",
  REMIND_AT_REQUIRED_UI: "remind_at is required.",
  FAILED_CREATE_TASK: "Failed to create task.",
  FAILED_ADD_REMINDER: "Failed to add reminder.",
  SAVE_FAILED: "Save failed.",
  ACTION_FAILED: "Action failed.",
  PUSHOVER_TEST_BUTTON: "Send Pushover Test",
  PUSHOVER_TEST_SENT: "Pushover test sent",
  PUSHOVER_TEST_FAILED: "Pushover test failed",
  PUSHOVER_TEST_REQUEST_FAILED: "Failed to send Pushover test",
  TASK_RESTORE_FAILED: "Task restore failed.",
  REMINDER_RESTORE_FAILED: "Reminder restore failed.",
  TASK_REMOVE_FAILED: "Task remove failed.",
  EVENT_REMOVE_FAILED: "Event remove failed.",
  FILE_REMOVE_FAILED: "File remove failed.",
  NOTE_REMOVE_FAILED: "Note remove failed.",
  JOURNAL_REMOVE_FAILED: "Journal remove failed.",
  TASK_TOGGLE_FAILED: "Task toggle failed.",
  SUBTASK_TOGGLE_FAILED: "Subtask toggle failed.",
  CHECKLIST_UPDATE_FAILED: "Checklist update failed.",
  REMINDER_ACTION_FAILED: "Reminder action failed.",
  LOAD_TASKS_FAILED: "Failed to load tasks.",
  LOAD_SUBTASKS_FAILED: "Failed to load subtasks.",
  LOAD_SUPPLIES_FAILED: "Failed to load supplies.",
  LOAD_PRESETS_FAILED: "Failed to load presets.",
  LOAD_JOURNALS_FAILED: "Failed to load journals.",
  SUBTASK_NOT_FOUND: "Subtask not found.",
  CAPTURE_EMPTY: "capture is empty",
  REMINDER_EMPTY: "reminder is empty",
  CAPTURE_FAILED: "Capture failed.",
  REFRESH_FAILED_AFTER_SAVE: "Saved, but refresh failed. Please reload.",
  JOURNAL_SAVE_FAILED: "Journal save failed.",
  NOTE_SAVE_FAILED: "Note save failed.",
  NOTE_EMPTY: "note is empty",
  REMINDER_SAVE_FAILED: "Reminder save failed.",
  EDITING_JOURNAL: "Editing journal",
  EDITING_NOTE: "Editing note",
  EDITING_REMINDER: "Editing reminder",
  SAVED: "Saved.",
  SHARED_CONTENT_READY: "Shared content ready.",
  SHARED_FILE_READY: "Shared file attached.",
  SHARED_FILE_LOAD_FAILED: "Shared file expired or missing.",
  FILE_DROP_EMPTY: "Drop one file to attach.",
  ATTACH_FILE_FIRST: "Attach a file first.",
  FILE_DROP_SINGLE_FILE_ONLY: "Only one file can be attached.",
  FILE_DROP_EDIT_MODE_UNAVAILABLE: "File drop is unavailable while editing.",
  FILE_DROP_FOLDER_UNSUPPORTED: "Dropped folders are not supported.",
  ELLIPSIS: "...",
  TASKS: "Tasks",
  REMINDERS: "Reminders",
  EVENTS: "Events",
  JOURNALS: "Journals",
  NOTES: "Notes",
  FILES: "Files",
  FAX: "Fax",
  SETTINGS: "Settings",
  SUPPLIES: "Supplies",
  CAPTURE: "Capture",
  TASK_DETAIL: "Task Detail",
  REPEAT_BADGE: "Repeat",
  REPEATING_TASK_EDIT_NOTICE: "Repeating task. Edits apply to this task only.",
  REPEAT_SCOPE_CURRENT_ONLY: "Current only",
  REPEAT_SCOPE_THIS_AND_FUTURE: "This and future",
  RECURRENCE_HISTORY_TITLE: "History",
  RECURRENCE_HISTORY_PREFIX: "Series edited",
  REMINDER_DETAIL: "Reminder Detail",
  TASK_LIST: "Task list",
  NO_TASKS: "No tasks yet.",
  ADD_TASK: "Add task",
  ADD_REMINDER: "Reminder",
  ADD: "Add",
  ADDING: "Adding...",
  SAVE: "Save",
  SAVING: "Saving...",
  DONE: "Done",
  UNDO: "Undo",
  BACK_TO_TASKS: "< Back to Task",
  BACK_TO_TASKS_LIST: "< Back to Tasks List",
  BACK_TO_REMINDERS_LIST: "< Back to Reminders List",
  TASK_NOT_FOUND: "Task not found.",
  REMINDER_NOT_FOUND: "Reminder not found.",
  JOURNAL_NOT_FOUND: "Journal not found.",
  BACKEND_UNREACHABLE: "backend unreachable",
  REMINDER_LIST: "Reminders",
  REMINDER_SHORT: "r",
  NO_REMINDERS: "No reminders.",
  NO_JOURNALS: "No journals yet.",
  NO_NOTES: "No notes yet.",
  NEW_NOTE_MODAL_TITLE: "New Note",
  ACK: "Ack",
  SNOOZE_10M: "Snooze 10m",
  CANCEL: "Cancel",
  COMPLETE: "Complete",
  ATTACH_ICON: "+",
  ATTACH_FILE: "Attach file",
  ATTACHMENT_EDIT_MODE_UNAVAILABLE: "Attachment is only available in Add mode.",
  SCRIBBLE_PROMPT: "This does not match capture grammar. Send it to Scribble?",
  SCRIBBLE_SAVE_FAILED: "Could not save Scribble.",
  SCRIBBLE_SENT: "Sent to Scribble.",
  SCRIBBLE: "Scribble",
  DASHBOARD_TITLE: "Dashboard",
  DASHBOARD_LOADING: "Loading dashboard...",
  DASHBOARD_LOAD_FAILED: "Failed to load dashboard.",
  TODAY_EVENTS: "Today events",
  UPCOMING_EVENTS: "Upcoming events",
  TASK_SUMMARY: "Task summary",
  TODAY_REMINDERS: "Today reminders",
  NO_TODAY_EVENTS: "No events today.",
  NO_UPCOMING_EVENTS: "No upcoming events.",
  NO_TODAY_REMINDERS: "No reminders today.",
  OVERDUE: "Overdue",
  TODAY: "Today",
  ACTIVE_TOTAL: "Active",
  SCRIBBLE_CARD_EMPTY: "Scribble card is empty.",
  SCRIBBLE_COPIED: "Copied Scribble text.",
  SCRIBBLE_COPY_FAILED: "Copy failed.",
  SCRIBBLE_DELETE_CONFIRM: "Delete this Scribble card?",
  SCRIBBLE_DELETE_FAILED: "Delete failed.",
  SCRIBBLE_DELETED: "Deleted Scribble card.",
  SCRIBBLE_STATUS_LOADING: "loading...",
  SCRIBBLE_STATUS_SAVING: "saving",
  SCRIBBLE_STATUS_ERROR: "save failed",
  SCRIBBLE_STATUS_SAVED: "saved",
  SCRIBBLE_CREATED_UNKNOWN: "Unknown datetime",
  SCRIBBLE_EMPTY_CARD: "Empty Scribble card",
  SCRIBBLE_LOADING_CARDS: "Loading Scribble cards...",
  SCRIBBLE_DESCRIPTION: "Transient scratch cards for messy capture before it becomes a task, event, journal entry, note, file, or disappears.",
  SCRIBBLE_EMPTY_STATE: "Unknown capture text sent to Scribble appears here as temporary workspace cards until you classify or delete it.",
  CAPTURE_TYPE: "Type",
  DATE_REQUIRED: "Date is required.",
  DATETIME_REQUIRED: "Datetime is required.",
  BODY_REQUIRED: "Body is required.",
  DATE_FORMAT_HINT: "Use yyyy-mm-dd format.",
  DATETIME_FORMAT_HINT: "Use yyyy-mm-dd HH:MM format.",
  GENERATED_RAW_EMPTY: "Generated raw is empty.",
  TOP_CAPTURE_FILE_HINT: "Use the unified top capture bar (attach + Add) to attach new files.",
  REMOVE_FILE_CONFIRM: "Move this file to Removed?",
  REMOVE_EVENT_CONFIRM: "Move this event to Removed?",
  HOLIDAY_BADGE: "Holiday",
  EVENT_BADGE: "Event",
  MARKET_BADGE: "Market",
  CLAIM_BADGE: "Claim",
  READONLY_BADGE: "Read-only",
  READONLY_EVENT_NOTICE: "System holiday events are read-only.",
  PUBLIC_HOLIDAY_LABEL: "Public holiday",
  CLASSIFICATION_SAVE_FAILED: "Classification save failed.",
  REMOVE_NOTE_CONFIRM: "Move this note to Removed?",
  REMOVE_TASK_CONFIRM: "Move this task to Removed?",
  COMPLETE_UNFIRED_REMINDER_CONFIRM: "This reminder has not fired yet. Completing it now will prevent it from firing and move it to Fired / Completed.",
  RESTORE: "Restore",
  FILE_SELECTED_FALLBACK: "selected file",
  FILE_TITLE_FALLBACK: "file",
  FILE_UPLOAD_FAILED: "File upload failed.",
  FILE_READ_FAILED: "Could not read attached file.",
  FILE_UPLOAD_REQUEST_FAILED: "File upload request failed.",
  FILE_METADATA_SAVE_REQUEST_FAILED: "File metadata save request failed.",
  INVALID_FILE_GRAMMAR: "Invalid file grammar.",
  FILE_GRAMMAR_INVALID: "Invalid file grammar.",
  FILE_GRAMMAR_TITLE_PREFIX_REQUIRED: "File title line must start with ++",
  FILE_GRAMMAR_TITLE_REQUIRED: "File title is required.",
  FILE_GRAMMAR_INVALID_LINE: "Only #tags, l:links, x:fax, and memo blocks are allowed after ++ title.",
  FILE_GRAMMAR_MEMO_UNCLOSED: 'Memo block must close with """.',
  ACTIVE: "active",
  DONE_STATE: "done",
  DUE: "d",
  MEMO: "Memo",
  CREATED: "created",
  UPDATED: "updated",
  STATE: "state",
  REMIND_AT: "remind_at",
  RAW_EDIT: "Raw Edit",
  TITLE: "title",
  EDIT_TASK: "Edit",
  MORE: "More",
  ID: "item ID",
  COPY_ID: "Copy ID",
  COPIED: "ID copied",
  TASKS_ACTIVE_TITLE: "Tasks • Active",
  TASK_ROUTINES_TITLE: "Routines",
  TASK_ONE_OFF_TITLE: "Tasks",
  TASKS_DONE_TITLE: "Tasks • Done",
  TASKS_REMOVED_TITLE: "Tasks • Removed",
  TASKS_ARCHIVED_TITLE: "Tasks • Archived",
  REMINDERS_ACTIVE_TITLE: "Reminders • Active",
  REMINDERS_FIRED_TITLE: "Reminders • Fired / Completed",
  REMINDERS_REMOVED_TITLE: "Reminders • Removed",
  REMINDER_BUTTON: "Reminder",
  EDIT_BUTTON: "Edit",
  MORE_BUTTON: "More",
  REMOVE_BUTTON: "Remove",
  REMOVED_STATE: "removed",
  REMOVED_TASK_READONLY: "Removed task is read-only.",
  DONE_UNKNOWN_MONTH: "Unknown",
};
