export const UI_STRINGS = {
  APP_TITLE: "KaosGdd Web",
  TASKS: "Tasks",
  TASK_DETAIL: "Task detail",
  TASK_LIST: "Task list",
  NO_TASKS: "No tasks yet.",
  ADD_TASK: "Add task",
  ADD_REMINDER: "Add reminder",
  ADD: "Add",
  ADDING: "Adding...",
  DONE: "Done",
  UNDO: "Undo",
  BACK_TO_TASKS: "← back to tasks",
  TASK_NOT_FOUND: "Task not found.",
  BACKEND_UNREACHABLE: "backend unreachable",
  REMINDER_LIST: "Reminders",
  NO_REMINDERS: "No reminders.",
  ACK: "Ack",
  SNOOZE_10M: "Snooze 10m",
  CANCEL: "Cancel",
  ACTIVE: "active",
  DONE_STATE: "done",
  DUE: "due",
  MEMO: "memo",
  CREATED: "created",
  UPDATED: "updated",
  STATE: "state",
  REMIND_AT: "remind_at",
};